var lh = lh || {};
lh.siteSettings = {
    "uuid": "e271783f52a74b7c9502618e332d7730",
    "uid" : "04723854-154e-45c2-a1f7-7478242c2012",
    "showOnce": "1",
    "convertOnce": "1",
    "language": "",
    "active":"0",
    "widgetTriggerButton":3,
    "widgetTriggerButtonStyle":"widget-phone-button",
    "branding": false,
    "speed": "0.225",
    "topBuffer": "0.0",
    "sideDetection": "top",
    "trackingAlgorithm": "default",
    "overlayPercent": 60,
    "overlayColor": "#000000",
    "title": "Вы нашли то, что искали?",
    "title_hide": "false",
    "callbackButtonText": "Мне позвонили",
    "callbackTitle": "Мы можем перезвонить в течение 25 секунд, готовы?",
    "description" : "Мы искренне ценим вас. Нам важно ваше мнение, чтобы стать лучше.",
    "thankYouTitle": "Спасибо Вам за звонок.",
    "thankYouDescription" : "Мы искренне ценим вас. Нам важно ваше мнение, чтобы стать лучше.",
    "mobileTimer": "0",
    "desktopTimer": "0",
    "callbackTime": "25",
    "widgetBodyColor": "#f3f3f3",
    "widgetTextColor": "#000000",
    "widgetButtonColor": "#3a5c89",
    "widgetButtonOverColor": "#474747",
    "widgetButtonText": "Жду звонка",
    "widgetButtonTextColor": "#f3f3f3",
    "widgetButtonOverTextColor": "#ffffff",
    "widgetPhoneMask": "+7 (999) 999-9999",
    "translucency": "1.0",
    "form_redirect": "none",
    "timezone": "-5.0",
    "double_opt_link_text": "No thanks, not interested.",
    "double_opt_button_text": "Yes! I want this!",
    "geoloc_radius": "50",
    "geoloc_center": "anywhere"
}
